In [28]:
import numpy as np
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(2,3))
print(a)
print('-'*15)

print(b)
print('-'*15)

print(a+b)
print('-'*15)

print(a-b)
print('-'*15)

print(a*b)
print('-'*15)

print(a/b)
print('-'*15)

print(a*5)
print('-'*15)

print(a>b)
print('-'*15)

[[7 6 1]
 [1 9 4]]
---------------
[[1 9 9]
 [4 2 4]]
---------------
[[ 8 15 10]
 [ 5 11  8]]
---------------
[[ 6 -3 -8]
 [-3  7  0]]
---------------
[[ 7 54  9]
 [ 4 18 16]]
---------------
[[7.         0.66666667 0.11111111]
 [0.25       4.5        1.        ]]
---------------
[[35 30  5]
 [ 5 45 20]]
---------------
[[ True False False]
 [False  True False]]
---------------


In [31]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [35]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr)
print(arr.mean())
print(arr.sum())
print(arr.std())
print(arr.var())
print(arr.min())
print(arr.max())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
9.5
171
5.188127472091127
26.916666666666668
1
18


In [41]:
arr = np.arange(10)

print(np.sqrt(arr))
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [43]:
a = np.random.randint(1,10,(2,3))

np.savetxt("./data/score.csv",a)